--Create a sequence starting with one.

CREATE SEQUENCE sequence_game1 START 1;

--Primary key of the games table is generated by sequence.
CREATE TABLE GAMES(game_id INTEGER DEFAULT nextval('sequence_game1') PRIMARY KEY, Game_name text , Game_date DATE);


--Game auto-incremented.

INSERT INTO GAMES(Game_name,Game_date) VALUES ('ICC CHAMPIONS TROPHY 3' ,'2017-06-15');
INSERT INTO GAMES(Game_name,Game_date) VALUES ('FIFA WORLD CUP' ,'2018-06-15');
                         
select * FROM GAMES;   