CREATE TABLE CITY 
  (
    CITY_CODE NUMERIC(5),
    CITY_NAME TEXT  
    );

CREATE UNIQUE INDEX uidx_city_name ON CITY USING BTREE(LOWER(CITY_NAME)) ; 


INSERT INTO CITY(CITY_CODE, CITY_NAME) 
  VALUES( 202 , 'Mumbai'), (204, 'Mangalore');
 
-- use on conflict to avoid unique constraint error. 
INSERT INTO CITY(CITY_CODE, CITY_NAME) 
  VALUES( 202 , 'MUMBAI'), (204, 'MANGALORE')
   ON CONFLICT(lower(CITY_NAME))  
 DO UPDATE SET CITY_NAME = EXCLUDED.CITY_NAME, CITY_CODE = EXCLUDED.CITY_CODE;
 
 SELECT * FROM CITY;